// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXpyrSCU6Nec55jxndijOflB-bAOEOBAg',
    appId: '1:911294411472:web:e4754e3ad66cc7eac964d5',
    messagingSenderId: '911294411472',
    projectId: 'conversation-3f896',
    authDomain: 'conversation-3f896.firebaseapp.com',
    storageBucket: 'conversation-3f896.appspot.com',
    measurementId: 'G-N63WKT3JF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRGIG2dpk1oQQfecXaioPJ_eKF3x0-x0',
    appId: '1:911294411472:android:63cb139cb9a0ab4bc964d5',
    messagingSenderId: '911294411472',
    projectId: 'conversation-3f896',
    storageBucket: 'conversation-3f896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzG5IY8P-tLHWNws76GV13H4Xkaq8ibkM',
    appId: '1:911294411472:ios:c0aae3cad42c165cc964d5',
    messagingSenderId: '911294411472',
    projectId: 'conversation-3f896',
    storageBucket: 'conversation-3f896.appspot.com',
    iosBundleId: 'com.example.conversation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzG5IY8P-tLHWNws76GV13H4Xkaq8ibkM',
    appId: '1:911294411472:ios:5d0fc58176ced2f7c964d5',
    messagingSenderId: '911294411472',
    projectId: 'conversation-3f896',
    storageBucket: 'conversation-3f896.appspot.com',
    iosBundleId: 'com.example.conversation.RunnerTests',
  );
}
